name: venv_bolus
channels:
#  - https://repo.anaconda.cloud/repo/scheldestromen/standard  # Tijdelijk - voor aangepaste geolib
  - anaconda
  - defaults
dependencies:
  - python==3.13
  - openpyxl==3.1.5
  - shapely>=2.0.6,<3
  - pip>=25.0
  - pip:
#    - d-geolib==2.6.0  # Tijdelijk - voor aangepaste geolib
    - git+https://github.com/KentropDevelopment/GEOLib.git@240-fix-connect-layers  # Tijdelijk - is de aangepaste geolib
    - pydantic==2.10.2