name: venv_bolus
channels:
  - https://repo.anaconda.cloud/repo/scheldestromen/standard
  - anaconda
  - defaults
dependencies:
  - python==3.13
  - openpyxl==3.1.5
  - shapely>=2.0.6,<3
  - pip>=25.0
  - pip:
    - d-geolib==2.6.0
    - pydantic==2.10.2